### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by felipenmoura**

### CODE REVIEW

**Comment by iamstarkov** [comment]
Needs a +1 from a native speaker.

**Comment by felipenmoura** [comment]
I am a native speaker :p
but ok, once a second opinion is always for the best :)

**Comment by remy** [comment]
Its nothing against your good self, just part of the contributing rules for
merging :)

**Comment by MattiSG** [comment]
Thanks for your contribution and reviews! There were conflicts with the base branch, I merged this through ed0c6d2 :)

**Pull request closed without merging**
