### PR TITLE
German version: Teilnehmer -> Teilnehmer_innen

### PR DESCRIPTION
**Pull request by katsel**
That one slipped your attention

### CODE REVIEW

**Comment by katsel** [comment]
ping @skade

**Comment by skade** [comment]
Right, that needs to be changed. I sadly have no commit access to the project.

@remy, can you merge?

Thanks for noticing!

**Comment by remy** [comment]
On it.

**Comment by remy** [comment]
IIRC, deployment is automated, but if you can double check that the change is live in the next minute or so, I'd appreciate it.

**Comment by katsel** [comment]
It's live! Thanks everybody!

**Pull request merged**
