### PR TITLE
Conf to org

### PR DESCRIPTION
**Pull request by Meandmybadself**
* Removed non-english CoC's until we agree on a base English version.
* Updated references to conference-centric event to better suit MJD organzation.

### CODE REVIEW

**Comment by Meandmybadself** [comment]
# What happened
Was using [pull-req](https://www.npmjs.com/package/pull-req), which erroneously opened a pull request against origin master instead of my organization's fork.  I've notified the author of that library that it has a bug.

# What we've done & our rationale
We run an organization for junior developers and needed verbiage that better reflected the our generalized needs.  Is still a work-in-progress.  It may be a better use of your time to have a look at our fork once we have the opportunity to review & discuss, as my working copy is a first draft.
Regardless, you can see the work-in-progress [here](https://github.com/mplsjrdevs/confcodeofconduct.com/pull/1).

**Comment by MattiSG** [comment]
Great, thanks a lot for these details! 🙂 And best of luck with your junior dev org (what's its name / homepage btw?).

**Comment by Meandmybadself** [comment]
Thanks! http://mplsjrdevs.com/

**Comment by MattiSG** [comment]
Nice! You might be interested in codebar.io to leverage some default content there 🙂 Let me know if I can help you connect in any way.

**Pull request closed without merging**
