### PR TITLE
index.html: Include staff badges

### PR DESCRIPTION
**Pull request by RichiH**
promcon.io might not have staff shirts, only staff badges, and thus we couldn't comply with the the COC's letter, only its presumed spirit.

### CODE REVIEW

**Comment by RichiH** [comment]
While this may be overthinking things, at FOSDEM, we also wear hoodies. "branded clothing and/or badges" might be best.

**Comment by remy** [comment]
Do you want to update to "branded clothing" as you suggested?

**Comment by RichiH** [comment]
Sure, sec.

**Comment by RichiH** [comment]
See https://github.com/confcodeofconduct/confcodeofconduct.com/pull/119

**Pull request closed without merging**
