### PR TITLE
Update index-es.html

### PR DESCRIPTION
**Pull request by mogox**
Adding a literal translation.  I feel that the previous one is shorter but it's not appropriate for a code of conduct.

### CODE REVIEW

**Comment by mogox** [comment]
Just reviewed the history and the previous version matches the original note on the TLDR, still I feel the new one is better.

**Comment by remy** [comment]
Needs +1 from another native speaker.

**Comment by alan-andrade** [comment]
Wow, esto esta mucho mejor !  So much better. :+1:

**Comment by mogox** [comment]
Thank you! @alan-andrade

**Comment by MattiSG** [comment]
Thanks! 🇪🇸

**Pull request merged**
