### PR TITLE
[ES] Little style correction

### PR DESCRIPTION
**Pull request by edgamen**
Contento was changed for encantado, because it's more contextual and natural in Spanish.
Another option to use is complacido.
Se cambia contento por encantado, ya que esta mejor contextualizado y es menos literal.
Otra opcion es complacido.

### CODE REVIEW

**Comment by MattiSG** [comment]
Thank you very much for this suggestion @edgamen! We need another native speaker to review this.

@sergiodxa, you recently opened #139, would you have 2 minutes to review this very short PR? 😃

**Comment by edgamen** [comment]
@sergiodxa 
Aunque no estoy de acuerdo con que "encantado" no sea una expresión adecuada en el contexto del documento, ya que estamos interpretando o traduciendo un "happy" (que indica una sensación de bienestar o agrado en la ejecución de una tarea); tampoco veo mal el uso de la expresión "dispuesto"  solamente. La expresión "más que dispuesto" si me parece exagerada.

El personal de la conferencia estará dispuesto **_a_** ayudar a los participa**_n_**tes 
El personal de la conferencia estará más que dispuesto **_a_** ayudar a los participa**_n_**tes

Although I do not agree that "encantado" is not an adequate expression in the context of the document, since we are interpreting or translating a "happy" (which indicates a feeling of well-being or pleasure in the execution of a task); nor do I see any misuse of the expression "dispuesto" alone. The expression "mas que dispuesto" seems exaggerated to me.

El personal de la conferencia estará dispuesto **_a_** ayudar a los participa**_n_**tes 
El personal de la conferencia estará más que dispuesto **_a_** ayudar a los participa**_n_**tes

**Comment by MattiSG** [comment]
From what I understand of this discussion: I believe the English “will be happy to” is here mostly as a polite way of saying “will be available to”; but that in this context, it is actually useful to insist on the fact that the organisers will be _happy to make themselves available_.
In the French translation, it is “seront _ravis_” (which I would translate as _encantados_). I find this slightly over-the-top in that language, and I would translate that back to English more as _delighted_ than as _happy to_ (i.e. actively looking forward for the opportunity to escort a harassed person…).

I feel that the aim would be to convey this idea of “the organisers are happy to make themselves available for [escorting someone]” rather than “will be happy to [escort someone]”.

**Comment by MattiSG** [comment]
In any case, thanks for taking the time to find the proper wording ❤️

**Comment by MattiSG** [comment]
@sergiodxa @edgamen can we reach a consensus on this small change? 🙂

**Comment by sergiodxa** [comment]
I agree with the usage of `dispuesto` as suggested by @edgamen in his last comment.

**Comment by MattiSG** [comment]
Excellent! @edgamen do you feel like updating the PR accordingly so we can get it merged? 😃

**Comment by edgamen** [comment]
Yes, no problem.

**Comment by MattiSG** [comment]
@edgamen great! Did you close this one on purpose though? 😕

**Pull request closed without merging**
