### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by PBartrina**
Translated into catalan.

Improvements accepted. 

Thanks for creating this,

Pau

### CODE REVIEW

**Review by MattiSG — CHANGES_REQUESTED** [review]
Thank you for this translation @PBartrina! We'll need a review by another native speaker 🙂 Feel free to mention others here if you know any! I've scheduled a tweet to request such help.

In the meantime, could you please remove the `.idea` and `package-lock.json` files that were added in this PR? Let's stay focused on translations 🙂

**Comment by remy** [comment]
This failed the first preview deploy, but I manually triggered (after having updated the base netlify image) and it's working here: https://deploy-preview-171--confcodeofconduct.netlify.app/ - I suspect further commits will also work

**Comment by PBartrina** [comment]
Sure thing @MattiSG , I'll remove them and push a commit right away

Thank you @remy for your fast work!

**Review by jonatanfm — APPROVED** [review]
As a native Catalan I didn't find any spell nor grammar issue.

**Review by FerranReby — APPROVED** [review]
As a native speaker the message is clear and concise. Very good translation!

**Review by MattiSG — APPROVED** [review]
You are all a bunch of lovely folks, thank you for this super fast review process @jonatanfm @FerranReby, and congratulations @PBartrina for your flawless translation and thanks for your quick correction on additional files 😊

**Pull request merged**
